ApiManager.Web/Models/ShareViewModel.cs
using ApiManager.Logic.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ApiManager.Web.Models
{
    public class ShareViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        
        [Required]
        [Display(Name = "UNC Path")]
        public string UNCPath { get; set; }

        [Required]
        public int Amount { get; set; }

        [Required]
        public Unit Unit { get; set; }

        [Display(Name = "Monitor Inactivity")]
        public bool MonitorInactivity { get; set; }
    }
}

ApiManager.Web/Controllers/Api/ShareController.cs
using ApiManager.Logic.Common;
using ApiManager.Logic.Models;
using ApiManager.Logic.Repositories;
using ApiManager.Web.Models.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Web.Http;

namespace ApiManager.Web.Controllers.Api
{
    public class ShareController : ApiController
    {
        private readonly ShareRepository shareRepository = new ShareRepository();

        [Route("api/share")]
        [HttpPost]
        public IHttpActionResult Get(FormDataCollection data)
        {
            string searchString = data["query[generalsearch]"];
            string sortOrder = data["sort[field]"] + "." + data["sort[sort]"];

            var items = shareRepository.List(sortOrder, searchString);

            List<ShareApiModel> services = new List<ShareApiModel>();
            foreach (var item in items)
            {
                services.Add(new ShareApiModel()
                {
                    Id = item.Id,
                    Name = item.Name,
                    UNCPath = item.UNCPath,
                    MonitorInactivity = item.MonitorInactivity
                });
            }

            return Ok(services);
        }


        [Route("api/share/create")]
        [HttpPost]
        public IHttpActionResult Create(FormDataCollection data)
        {
            try
            {

                var share = new Share();

                var monitorInactivity = false;
                if (data["MonitorInactivity"] == "true,false")
                {
                    monitorInactivity = true;
                }

                share.Name = data["Name"];
                share.UNCPath = data["UNCPath"];
                var inactivityTimeout = new Interval(Convert.ToInt32(data["Amount"]), (Unit)Enum.Parse(typeof(Unit), data["Unit"]));
                share.InactivityTimeout = inactivityTimeout;
                share.MonitorInactivity = monitorInactivity;

                shareRepository.Insert(share);

                return Ok();

            }
            catch (Exception e)
            {

                return BadRequest(e.Message);
            }
        }

        [Route("api/share/edit")]
        [HttpPost]
        public IHttpActionResult Edit(FormDataCollection data)
        {
            try
            {

                var share = shareRepository.GetById(Convert.ToInt32(data["Id"]));

                var monitorInactivity = false;
                if (data["MonitorInactivity"] == "true,false")
                {
                    monitorInactivity = true;
                }

                share.Name = data["Name"];
                share.UNCPath = data["UNCPath"];
                var inactivityTimeout = new Interval(Convert.ToInt32(data["Amount"]), (Unit)Enum.Parse(typeof(Unit), data["Unit"]));
                share.InactivityTimeout = inactivityTimeout;
                share.MonitorInactivity = monitorInactivity;

                shareRepository.Update(share);

                return Ok();

            }
            catch (Exception e)
            {

                return BadRequest(e.Message);
            }
        }

    }
}

ApiManager.Web/Controllers/ShareController.cs
using ApiManager.Logic.Repositories;
using ApiManager.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApiManager.Web.Controllers
{
    [Authorize]
    public class ShareController : Controller
    {
        private readonly ShareRepository shareRepository = new ShareRepository();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            try
            {
                var item = shareRepository.GetById(id);

                var model = new ShareViewModel()
                {
                    Id = item.Id,
                    Name = item.Name,
                    Amount = item.InactivityTimeout.Amount,
                    Unit = item.InactivityTimeout.Unit,
                    MonitorInactivity = item.MonitorInactivity,
                    UNCPath = item.UNCPath
                };

                return View(model);
            }
            catch (Exception e)
            {

                throw;
            }
        }

        public ActionResult Create()
        {
            return View();
        }

    }
}

ApiManager.Web/Views/Share/Create.cshtml
@model ApiManager.Web.Models.ShareViewModel

@{
    ViewBag.Title = "Create Share";
}

<div class="row">
    <div class="col-lg-12">

        <!--begin::Portlet-->
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">Create Share</h3>
                </div>
            </div>

            <!--begin::Form-->
            @using (Html.BeginForm("Create", "Share", FormMethod.Post, new { @class = "kt-form kt-form--label-right", @id = "kt_share_form" }))
            {
                <div class="kt-portlet__body">
                    <div class="form-group row">
                        <div class="col-lg-6">
                            @Html.LabelFor(model => model.Name)
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                         </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-6">
                            @Html.LabelFor(model => model.UNCPath)
                            @Html.EditorFor(model => model.UNCPath, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-6">
                            @Html.LabelFor(model => model.MonitorInactivity)
                            <div class="kt-checkbox-inline">
                                @Html.EditorFor(model => model.MonitorInactivity)
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-2">
                            <label>Inactivity Timeout</label>
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                        <div class="col-lg-2">
                            <label>&nbsp;</label>
                            @Html.EnumDropDownListFor(model => model.Unit, "- Select unit -", new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                        <div class="row">
                            <div class="col-lg-12">
                                <button type="submit" class="btn btn-primary" data-ktwizard-action="action-submit">Save</button>
                                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/dist/assets/js/pages/custom/shares/create.js" type="text/javascript"></script>
    <script type="text/javascript">



    </script>
}

ApiManager.Web/Views/Share/Edit.cshtml
@model ApiManager.Web.Models.ShareViewModel

@{
    ViewBag.Title = "Edit Share";
}

<div class="row">
    <div class="col-lg-12">

        <!--begin::Portlet-->
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">Edit Share</h3>
                </div>
            </div>

            <!--begin::Form-->
            @using (Html.BeginForm("Edit", "Share", FormMethod.Post, new { @class = "kt-form kt-form--label-right", @id = "kt_share_form" }))
            {
                @Html.HiddenFor(model => model.Id)

                <div class="kt-portlet__body">
                    <div class="form-group row">
                        <div class="col-lg-6">
                            @Html.LabelFor(model => model.Name)
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                         </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-6">
                            @Html.LabelFor(model => model.UNCPath)
                            @Html.EditorFor(model => model.UNCPath, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-6">
                            @Html.LabelFor(model => model.MonitorInactivity)
                            <div class="kt-checkbox-inline">
                                @Html.EditorFor(model => model.MonitorInactivity)
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-2">
                            <label>Inactivity Timeout</label>
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                        <div class="col-lg-2">
                            <label>&nbsp;</label>
                            @Html.EnumDropDownListFor(model => model.Unit, "- Select unit -", new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                        <div class="row">
                            <div class="col-lg-12">
                                <button type="submit" class="btn btn-primary" data-ktwizard-action="action-submit">Save</button>
                                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/dist/assets/js/pages/custom/shares/edit.js" type="text/javascript"></script>
    <script type="text/javascript">



    </script>
}

ApiManager.Web/Views/Share/Index.cshtml
@{
    ViewBag.Title = "Shares";
}

<h2>Index</h2>

<div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title">
                Shares
                <small>show list of shares</small>
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-wrapper">
                <a href="/share/create" class="btn btn-brand btn-bold btn-upper btn-font-sm">
                    <i class="la la-plus"></i>
                    New Share
                </a>
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">

        <!--begin: Search Form -->
        <div class="kt-form kt-fork--label-right kt-margin-t-20 kt-margin-b-10">
            <div class="row align-items-center">
                <div class="col-xl-8 order-2 order-xl-1">
                    <div class="row align-items-center">
                        <div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
                            <div class="kt-input-icon kt-input-icon--left">
                                <input type="text" class="form-control" placeholder="Search..." id="generalSearch">
                                <span class="kt-input-icon__icon kt-input-icon__icon--left">
                                    <span><i class="la la-search"></i></span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 order-1 order-xl-2 kt-align-right">
                    <a href="/share/create" class="btn btn-default kt-hidden">
                        <i class="la la-cart-plus"></i> New Share
                    </a>
                    <div class="kt-separator kt-separator--border-dashed kt-separator--space-lg d-xl-none"></div>
                </div>
            </div>
        </div>

        <!--end: Search Form -->
    </div>
    <div class="kt-portlet__body kt-portlet__body--fit">

        <!--begin: Datatable -->
        <div class="kt_datatable" id="kt_share_list"></div>

        <!--end: Datatable -->
    </div>
</div>


@section scripts
{
    <script src="~/dist/assets/js/pages/custom/shares/list-datatable.js" type="text/javascript"></script>
}